#===============# BungeeAnnounce Configuration file #===============#
#
#Prefixes for all types of announcement (color codes supported!)
announce-prefix: ''
#
#=====================# Private messaging settings #=====================#
#If true, players will be able to do /msg <player> <message> on all servers
enable-private-message: true
#Which command players will have to use to communicate between servers (default is set to /msg)
#command-for-private-message: msg Deprecated, will always use /msg
#Private messages:
private-message-send: '&3Send to &e%RECEIVER%: &d%MESSAGE%'
private-message-received: '&3Received from &e%SENDER%: &d%MESSAGE%'
private-message-player-not-online: '&c%PLAYER% is unreachable :('
private-message-sender-equals-receiver: '&7Are you schizophrenic ? :O'
reply-info: '&7Use &a/reply &7to respond to &b%SENDER%'
#
#===========================# Logs settings #============================#
#Register each announcement sended by your staff team in a log (located at BungeeAnnounce/logs)
enable-announcement-logs: false
#
#====================# Scheduler announce settings #=====================#
#To create scheduled messages, you must follow this pattern:
# 'name(it can be whatever you want)':
#   permission: 'your.permission' (optional, if you want that only players with that permission are able to see this announcement)
#   interval: 10 (interval between each message in seconds. If negative, announcement will be frozen and can be triggered only by using command /fbc <announcement name>)
#   delay: 0 (time to wait after the plugin is loaded to begin the scheduled task in seconds)
#   message: 'message to display'
#   type: announce
#   servers: 
#     - 'server name on which the message will be displayed'
#	  put « - 'all' » if you want to display the message on all servers.
#
#Note: Use '[ln]' to go to the next line.
#A lot of placeholders are available to be used:
#You can get them at https://github.com/Royalphax/BungeeAnnounce/wiki/Placeholders
# 
#You can see 3 examples below ('action1', 'announce1' and 'vip1')
#You can delete/edit/copy&paste them.
scheduler:
  'announce1':
    interval: 30
    delay: 10
    message: '&aClick &bhere::run_command::/say_hello &ato say hello !'
    type: announce
    align: center
    servers:
      - 'all'