main: fr.royalpha.bungeeannounce.BungeeAnnouncePlugin
name: BungeeAnnounce
version: ${project.version}
author: Royalpha
commands:
  forcebroadcast:
    description: Force broadcast of an announcement
    permission: bungeecord.command.forcebroadcast
  "ba:reload":
    description: "Reload bungee announce's configuration"
    permission: bungeecord.command.reload
  announce:
    description: Send an announcement through all your network.
    permission: bungeecord.command.announce
  colorcode:
    description: Show a list of all color/format codes.